### ISSUE TITLE
Command required error

### ISSUE THREAD

**Issue by jkreinz** [IDEELResearch/vcfdo#8]
I've trying to use the polarize command but regardless of whether I pipe in the vcf or use the -i option, I always get the same error: 

`polarize: error: the following arguments are required: command`

in this case, I used the command  `bcftools view pseudo_qual_dust_indel_fixedmissing_nodups_resorted_nodups2.vcf.gz | vcfdo polarize -f path/to/AMATA_finishedtohypo_renamedfinal_doubleAAmod.fasta`

However I noticed this error occurs regardless of what command I try and use (e.g. treemix, pca, etc.). I'm wondering if it's an install issue because I initially had a NumPy version issue but I uninstall and reinstalled everything with pip and it seemed to install fine.

Thanks!

**Comment by andrewparkermorgan** [comment]
I think this was due to an error in specifying inheritance of command-line arguments to the various `vcfdo` subcommands. I just pushed a small change that should fix the problem

**Comment by jkreinz** [comment]
thanks! that did the trick!

**Comment by jkreinz** [comment]
I'm running into another error when I execute vcfdo sfs after having successfully polarized my vcf:

```
Traceback (most recent call last):
  File "/ohta1/julia.kreiner/software/miniconda3/lib/python3.8/site-packages/vcfdo/core.py", line 138, in fetch_region
    next_site = VcfSite( next(site_iter), self.assume_ref_ancestral )
  File "cyvcf2/cyvcf2.pyx", line 436, in __call__
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ohta1/julia.kreiner/software/miniconda3/lib/python3.8/site-packages/vcfdo/core.py", line 165, in fetch_region
    raise StopIteration
StopIteration
```

**Comment by diogofclima5** [comment]
Hi, [jkreinz](https://github.com/jkreinz)
Were you able to solve this problem?


> I'm running into another error when I execute vcfdo sfs after having successfully polarized my vcf:
> 
> ```
> Traceback (most recent call last):
>   File "/ohta1/julia.kreiner/software/miniconda3/lib/python3.8/site-packages/vcfdo/core.py", line 138, in fetch_region
>     next_site = VcfSite( next(site_iter), self.assume_ref_ancestral )
>   File "cyvcf2/cyvcf2.pyx", line 436, in __call__
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/ohta1/julia.kreiner/software/miniconda3/lib/python3.8/site-packages/vcfdo/core.py", line 165, in fetch_region
>     raise StopIteration
> StopIteration
> ```
